import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Shield, ArrowLeft, Phone, Lock, User, MapPin, IndianRupee, Bike } from 'lucide-react';
import './RegisterPage.css';
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_ANON_KEY
);

export function RegisterPage() {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    name: '',
    phone: '',
    zone: 'HSR Layout',
    platform: 'Swiggy',
    income: '7000',
    password: '',
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    // Clean phone number to only digits
    const cleanValue = name === 'phone' ? value.replace(/\D/g, '') : value;
    setFormData(prev => ({ ...prev, [name]: cleanValue }));
  };

  const handleRegister = async (e) => {
  e.preventDefault();

  // 👉 INSERT into Supabase and SELECT the returned row
  const { data, error } = await supabase
    .from("workers")
    .insert([
      {
        name: formData.name,
        phone: formData.phone,
        zone: formData.zone,
        platform: formData.platform,
        weekly_income: formData.income,
        password: formData.password,
      }
    ])
    .select(); // 👈 CRITICAL: This returns the newly created row with the ID

  if (error) {
    console.error(error);
    alert("Registration failed!");
    return;
  }

  if (data && data.length > 0) {
    const newUser = data[0];

    // ✅ SAVE THE DYNAMIC ID GENERATED BY SUPABASE
    localStorage.setItem("workerId", newUser.id); 
    localStorage.setItem("role", "worker");
    localStorage.setItem("workerName", newUser.name);
    localStorage.setItem("workerZone", newUser.zone);
    localStorage.setItem("workerIncome", newUser.weekly_income);
    localStorage.setItem("workerPhone", newUser.phone);
    localStorage.setItem("workerPlatform", newUser.platform);
    localStorage.setItem("isLoggedIn", "true");

    alert(`Account Created! Your ID is ${newUser.id}`);
    navigate('/dashboard');
  }
};

  return (
    <div className="register-page">
      <div className="register-container">
        <button className="back-btn" onClick={() => navigate('/login')}>
          <ArrowLeft size={20} />
        </button>

        <div className="register-header">
          <div className="register-logo">
            <Shield size={42} color="#00ff88" />
          </div>
          <h1>Create Account</h1>
          <p>Join 5,000+ protected gig workers</p>
        </div>

        <form className="register-form" onSubmit={handleRegister}>
          {/* FULL NAME */}
          <div className="form-group">
            <label>Full Name</label>
            <div className="input-wrapper">
              <User size={18} className="input-icon" />
              <input
                name="name"
                type="text"
                placeholder="Rajesh Kumar"
                value={formData.name}
                onChange={handleChange}
                required
              />
            </div>
          </div>

          {/* PHONE NUMBER */}
          <div className="form-group">
            <label>Phone Number</label>
            <div className="input-wrapper">
              <span className="prefix">+91</span>
              <input
                name="phone"
                type="tel"
                placeholder="9876543210"
                maxLength="10"
                value={formData.phone}
                onChange={handleChange}
                required
              />
            </div>
          </div>

          <div className="form-row">
            {/* ZONE */}
            <div className="form-group">
              <label>Work Zone</label>
              <div className="input-wrapper">
                <MapPin size={18} className="input-icon" />
                <select name="zone" value={formData.zone} onChange={handleChange}>
                  <option value="HSR Layout">HSR Layout</option>
                  <option value="Koramangala">Koramangala</option>
                  <option value="Whitefield">Whitefield</option>
                  <option value="Indiranagar">Indiranagar</option>
                </select>
              </div>
            </div>

            {/* PLATFORM */}
            <div className="form-group">
              <label>Platform</label>
              <div className="input-wrapper">
                <Bike size={18} className="input-icon" />
                <select name="platform" value={formData.platform} onChange={handleChange}>
                  <option value="Swiggy">Swiggy</option>
                  <option value="Blinkit">Blinkit</option>
                  <option value="Zepto">Zepto</option>
                </select>
              </div>
            </div>
          </div>

          {/* WEEKLY INCOME */}
          <div className="form-group">
            <label>Avg. Weekly Income (₹)</label>
            <div className="input-wrapper">
              <IndianRupee size={18} className="input-icon" color="#00ff88" />
              <input
                name="income"
                type="number"
                placeholder="7000"
                value={formData.income}
                onChange={handleChange}
                required
              />
            </div>
          </div>

          {/* PASSWORD */}
          <div className="form-group">
            <label>Security Password</label>
            <div className="input-wrapper">
              <Lock size={18} className="input-icon" />
              <input
                name="password"
                type="password"
                placeholder="••••••••"
                value={formData.password}
                onChange={handleChange}
                required
              />
            </div>
          </div>

          <button type="submit" className="btn-register">
            Secure My Income
          </button>
        </form>

        <p className="register-footer">
          Already protected? <span onClick={() => navigate('/login')}>Login</span>
        </p>
      </div>
    </div>
  );
}